#warnings-disable

extends Node2D

export var EXPLORATION_GRAVITY = 200
export var EXPLORATION_MOVE_SPEED = 200
export var EXPLORATION_JUMP_VELOCITY = 800
export var EXPLORATION_JUMP_X_MODIFIER = 1

export var COMBAT_GRAVITY = 200
export var COMBAT_MOVE_SPEED = 100
export var COMBAT_JUMP_VELOCITY = 700
export var COMBAT_JUMP_X_MODIFIER = 1.5
